# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.9
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: check-merge-conflict
    - id: check-json
    - id: check-yaml
    - id: check-added-large-files
    - id: no-commit-to-branch
      args: [--branch, main]
- repo: https://github.com/python-poetry/poetry
  rev: 1.3.2
  hooks:
    - id: poetry-check
    - id: poetry-lock
      args: [--no-update]
    - id: poetry-export
      args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
    language_version: python3
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: poetry run pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-j 0", # Use all CPUs
        ]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
# - repo: https://github.com/PyCQA/bandit
#   rev: 1.7.4
#   hooks:
#   - id: bandit
#     name: bandit
#     description: 'Bandit is a tool for finding common security issues in Python code'
#     entry: bandit
#     language: python
#     language_version: python3
#     types: [ python ]
- repo: local
  hooks:
  - id: unittests
    name: unit tests
    entry: poetry run pytest
    language: system
    pass_filenames: false
    args: []
